# Generated by Django 4.2.5 on 2023-10-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='EstateOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=200)),
                ('identity_number', models.CharField(blank=True, max_length=11, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_status', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FromWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_who', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=30)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.county')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('estate_number', models.CharField(max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('m2_brut', models.CharField(max_length=10)),
                ('m2_net', models.CharField(max_length=10)),
                ('heating', models.CharField(max_length=100)),
                ('using_status', models.CharField(blank=True, max_length=10, null=True)),
                ('building_years', models.CharField(max_length=10)),
                ('building_floor', models.CharField(max_length=10)),
                ('location_floor', models.CharField(max_length=10)),
                ('bathrooms_count', models.CharField(max_length=10)),
                ('within_site', models.BooleanField(default=False)),
                ('site_name', models.CharField(blank=True, max_length=75, null=True)),
                ('is_with_firniture', models.BooleanField(default=False)),
                ('dues', models.CharField(max_length=10)),
                ('is_available_for_loan', models.BooleanField(default=False)),
                ('is_balcony', models.BooleanField(default=False)),
                ('deed_status', models.CharField(max_length=100)),
                ('change', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.city')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.county')),
                ('estate_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.estateowner')),
                ('estate_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estatestatus')),
                ('estate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estatetype')),
                ('from_who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.fromwho')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.region')),
                ('room_count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.roomcount')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estate_images/')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.region')),
            ],
        ),
    ]
