# Generated by Django 4.2.5 on 2023-10-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromwho',
            name='from_who',
            field=models.CharField(choices=[('Emlakçıdan', 'Emlakçıdan'), ('Sahibinden', 'Sahibinden')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcount',
            name='room_count',
            field=models.CharField(choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('4+2', '4+2'), ('5+1', '5+1'), ('5+2', '5+2'), ('5+3', '5+3')], max_length=10, unique=True),
        ),
    ]
