# Generated by Django 4.2.5 on 2023-10-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateRenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=200)),
                ('identity_number', models.CharField(blank=True, max_length=11, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estateowner',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateTimeField(auto_now_add=True)),
                ('contract_duration', models.PositiveIntegerField()),
                ('year_rental_price', models.PositiveIntegerField()),
                ('mounth_rental_price', models.PositiveIntegerField()),
                ('rent_payment_method', models.CharField(max_length=200)),
                ('how_to_use_the_rented_property', models.CharField(max_length=200)),
                ('status_of_the_rented_property', models.CharField(max_length=200)),
                ('fixtures_delivered_with_the_rental', models.CharField(max_length=200)),
                ('estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.realestate')),
                ('estate_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.estateowner')),
                ('estate_renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.estaterenter')),
            ],
        ),
    ]
