# Generated by Django 4.2.5 on 2023-10-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_estaterenter_alter_estateowner_phone_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='estaterenter',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.realestate'),
        ),
    ]
