# Generated by Django 4.2.5 on 2023-10-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_estatetype_estate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatestatus',
            name='estate_status',
            field=models.CharField(choices=[('KIRALIK', 'Kiralık'), ('SATILIK', 'Satılık')], max_length=30, unique=True),
        ),
    ]
