# Generated by Django 4.2.5 on 2023-10-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_estatestatus_estate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatestatus',
            name='estate_status',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fromwho',
            name='from_who',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcount',
            name='room_count',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
