# Generated by Django 4.2.2 on 2023-09-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_county_remove_city_country_remove_region_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_name',
            field=models.CharField(max_length=100),
        ),
    ]
