# Generated by Django 4.2.5 on 2023-10-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_estaterenter_real_estate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estaterenter',
            name='real_estate',
        ),
        migrations.AddField(
            model_name='realestate',
            name='estate_renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.estaterenter'),
        ),
    ]
