# Generated by Django 4.2.5 on 2023-10-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_estatestatus_estate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatestatus',
            name='estate_status',
            field=models.CharField(choices=[('SATILIK', 'Satılık'), ('KIRALIK', 'Kiralık')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fromwho',
            name='from_who',
            field=models.CharField(choices=[('EMLAKCIDAN', 'Emlakçıdan'), ('SAHIBINDEN', 'Sahibinden')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='estate_status',
            field=models.ForeignKey(blank=True, choices=[('SATILIK', 'Satılık'), ('KIRALIK', 'Kiralık')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estatestatus'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='estate_type',
            field=models.ForeignKey(blank=True, choices=[('DAIRE', 'Daire'), ('VILLA', 'Villa'), ('RESIDENCE', 'Residence'), ('MUSTAKIL_EV', 'Müstakil Ev')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estatetype'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='from_who',
            field=models.ForeignKey(blank=True, choices=[('EMLAKCIDAN', 'Emlakçıdan'), ('SAHIBINDEN', 'Sahibinden')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.fromwho'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='room_count',
            field=models.ForeignKey(blank=True, choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+1', '2+1'), ('2+0', '2+0'), ('3+1', '3+1'), ('3+2', '3+2'), ('3+0', '3+0'), ('4+1', '4+1'), ('4+2', '4+2'), ('5+1', '5+1'), ('5+2', '5+2')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.roomcount'),
        ),
        migrations.AlterField(
            model_name='roomcount',
            name='room_count',
            field=models.CharField(choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+1', '2+1'), ('2+0', '2+0'), ('3+1', '3+1'), ('3+2', '3+2'), ('3+0', '3+0'), ('4+1', '4+1'), ('4+2', '4+2'), ('5+1', '5+1'), ('5+2', '5+2')], max_length=10, unique=True),
        ),
    ]
