# Generated by Django 4.2.2 on 2023-09-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_neighbourhood_neighbourhood_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FromWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_who', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('estate_number', models.CharField(max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('m2_brut', models.CharField(max_length=10)),
                ('m2_net', models.CharField(max_length=10)),
                ('using_status', models.CharField(max_length=10)),
                ('building_years', models.CharField(max_length=10)),
                ('building_floor', models.CharField(max_length=10)),
                ('bathrooms_count', models.CharField(max_length=10)),
                ('is_with_firniture', models.BooleanField(default=False)),
                ('dues', models.CharField(max_length=10)),
                ('is_available_for_loan', models.BooleanField(default=False)),
                ('is_balcony', models.BooleanField(default=False)),
                ('deed_status', models.CharField(max_length=100)),
                ('change', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.city')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.county')),
                ('estate_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estatestatus')),
                ('estate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estatetype')),
                ('from_who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.fromwho')),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.neighbourhood')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.region')),
                ('room_count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.roomcount')),
            ],
        ),
    ]
