# Generated by Django 4.2.5 on 2023-10-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_estaterenter_real_estate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='estate_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estateowner'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='estate_renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estaterenter'),
        ),
    ]
