# Generated by Django 4.2.5 on 2023-10-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_realestate_estate_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=200)),
                ('identity_number', models.CharField(blank=True, max_length=11, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='estate_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.estatebuyer'),
        ),
    ]
