# Generated by Django 4.2.2 on 2023-09-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_estatestatus_estatetype_fromwho_roomcount_realestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estate_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='address',
            name='Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.region'),
        ),
        migrations.AlterField(
            model_name='estatestatus',
            name='estate_status',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='estate_type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fromwho',
            name='from_who',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcount',
            name='room_count',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Neighbourhood',
        ),
        migrations.AddField(
            model_name='image',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.realestate'),
        ),
    ]
