# Generated by Django 4.2.5 on 2023-10-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_estatestatus_estate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='m2_brut',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='m2_net',
            field=models.PositiveIntegerField(),
        ),
    ]
