# Generated by Django 4.2.5 on 2023-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_contrat_estate_remove_contrat_estate_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='apartment_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='exterior_door_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
