# Generated by Django 4.2.5 on 2023-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_realestate_m2_brut_alter_realestate_m2_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='building_floor',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='building_years',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='location_floor',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
