# Generated by Django 4.2.2 on 2023-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_realestate_location_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='within_site',
            field=models.BooleanField(default=False),
        ),
    ]
