# Generated by Django 4.2.2 on 2023-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_realestate_within_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='heating',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
