# Generated by Django 4.2.5 on 2023-09-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_estateowner_address_estateowner_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateowner',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
